### ISSUE TITLE
PHP 8 Undefined array key "resetFilter" 

### ISSUE THREAD

**Issue by Daniel-Siteway** [Quebecca/qc_redirects#7]
Hi,
after installing this extension on a new Typo3 11 system with PHP 8.2 I get the following error when calling the redirect module in the Typo3 backend: 

Uncaught TYPO3 Exception: #1476107295: PHP Warning: Undefined array key "resetFilter" in /html/typo3/typo3conf/ext/qc_redirects/Classes/Controller/ExtendedRedirectModule/v11/ManagementControllerExt.php line 164 | TYPO3\CMS\Core\Error\Exception thrown in file /html/typo3/typo3_src-11.5.21/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 137. Requested URL: https://domain.de/typo3/module/site/redirects?token=--AnonymizedToken--

The extension was installed via the backend using Ter.
Is there a simple fix available?

System Info:
TYPO3: 11.5.21
Server: Apache
PHP-Version: 8.2.0

**Comment by gaumondp** [comment]
@Daniel-Siteway , did the last commit solve the error you got? 

If so, please simply close the bug report and thanks for letting us know.

**Comment by gaumondp** [comment]
We consider this issue as fixed.
